# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 05:03
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('class_id', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter class in the form of PHY 0011', regex='^[A-Z]{2,4} 0+[0-9]+$')])),
                ('edition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
