# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-19 19:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='class_id',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter class in the form of XXXX #### (e.x. PHY 0011)', regex='^[A-Z]{2,4} 0+[0-9]+$')]),
        ),
    ]
