# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 05:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tufts_id', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Please enter a valid Tufts ID number', regex='^[0-9]{7}$')])),
                ('venmo_username', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^[0-9]{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
